### ISSUE TITLE
Scope of params 'query_string' and 'all_words' unclear in the API endpoint 'GET /products/search'

### ISSUE THREAD

**Issue by thesolotraveller** [zandoan/turing-backend#1]
For the API endpoint **GET /products/search**, on link (https://backendapi.turing.com/docs/#/products), scope for params is unclear. Looking at it is not giving clear idea on what feature result to pull and send in response to that API request.

Looking forward for some clarifications on this.

**Comment by edertaveira** [comment]
So:
- 'query_string' is the string that you will search, like a "beautiful".
- 'all_word' is a flag indicating that you will search in all words using the signals before each word (+ to and, - to not). check in this link for more details (https://dev.mysql.com/doc/refman/5.5/en/fulltext-boolean.html)
