### ISSUE TITLE
GET /customer should have a param for customer_id to get detail for specific customer. Current it is missing.

### ISSUE THREAD

**Issue by thesolotraveller** [zandoan/turing-backend#2]
In API GET /customer, description says that it is to get customer by an id so shouldn't we be having customer_id params in url ??

**Comment by edertaveira** [comment]
Hi @thesolotraveller, No because the endpoint requires a private key in your header.
For more information check in this link, please: https://github.com/zandoan/turing-frontend#authentication

**Comment by azecharias** [comment]
You should use this end point only for logged in users. And those logged in users can only access their own data. Which means as long as you pass a valid jwt token in the header, you’ll be able to get the data of that user.

**Comment by mohit-actigage** [comment]
@edertaveira Yeah makes sense now. Didn't realize earlier which requests need a token and which don't till the point I saw the `lock` presence against requests, in docs, that need a token.

Thanks for clearing it.
